/*
This file providers an example client using generated stubs in directory `api`
 */

import { createRequire } from 'module'
import * as grpc from '@grpc/grpc-js'

/*
 The JavaScript code in the `api` directory generated by `grpc_tools_node_protoc` uses CommonJS-style require() statements to import and export modules.
 These modules are not compatible with ES module syntax (import/export).
 To use the generated code in an ES module, we use createRequire() from the module built-in module to import the generated code.
 */
const require = createRequire(import.meta.url)
const { PriceClient } = require('../api/grpc_grpc_pb.js')
const { MarketPriceRequest } = require('../api/grpc_pb.js')

function main() {
    const client = new PriceClient('192.168.1.230:9998', grpc.credentials.createInsecure())
    const request = new MarketPriceRequest()
    const metadata = new grpc.Metadata()

    // Token-based authentication, the token should be sent as a metadata item with each request
    metadata.add('password', '')
    // Set the parameter value
    request.setCurrencyCode('usd');

    client.getMarketPrice(request, metadata, function(err, response) {
        console.log('Market price:', response)
    })
}

main()

